import {
  Stethoscope,
  HardHat,
  Building2,
  Shield,
  Scale,
} from "lucide-react";

export const VIES_ES = [
  {
    id: "metge-familia",
    icon: Stethoscope,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-l-blue-500",
    badgeColor: "bg-blue-100 text-blue-800",
    title: "Alta del médico de familia (AP)",
    subtitle: "Reclamación administrativa previa — ICAM (Cataluña)",
    termini: "11 días hábiles",
    organisme: "ICAM / Inspección Médica",
    urgencia: "Alta",
    resum:
      "Cuando el médico de familia o un especialista del servicio público de salud emite un alta médica y el paciente no está de acuerdo, puede presentar una reclamación administrativa previa ante la Dirección General de Ordenación y Regulación Sanitaria (ICAM en Cataluña).",
    passos: [
      {
        num: 1,
        titol: "Presentar la reclamación",
        desc: "Escrito de reclamación administrativa previa dirigido a la Dirección General de Ordenación y Regulación Sanitaria del Departament de Salut. Se puede hacer por internet (ciudadanos obligados a relacionarse electrónicamente) o presencialmente.",
      },
      {
        num: 2,
        titol: "Plazo de presentación",
        desc: "11 días hábiles desde la fecha del alta médica (no cuentan sábados, domingos ni festivos). En otros supuestos de disconformidad (no alta), el plazo es de 30 días hábiles.",
      },
      {
        num: 3,
        titol: "Revisión por el ICAM",
        desc: "El ICAM (Inspección Médica) revisa el caso y puede confirmar el alta o emitir un nuevo comunicado de baja. La resolución se notifica a la persona interesada.",
      },
      {
        num: 4,
        titol: "Si la reclamación es denegada",
        desc: "Si el ICAM confirma el alta, el trabajador puede acudir a la vía judicial social (Juzgado de lo Social) en el plazo de 30 días hábiles desde la notificación de la resolución.",
      },
    ],
    documentacio: [
      "DNI/NIE de la persona solicitante",
      "Comunicado de alta médica original",
      "Documentación médica de apoyo (informes, pruebas diagnósticas)",
      "Documento de representación (si actúa en nombre de otra persona)",
    ],
    consells: [
      "La reclamación NO suspende el alta: el trabajador debe reincorporarse al trabajo mientras se espera la resolución.",
      "Conserva copia de toda la documentación médica previa al alta.",
      "Si tienes un médico especialista que no esté de acuerdo con el alta, pide un informe escrito.",
      "Puedes llamar al ICAM para consultar el estado de la reclamación: Barcelona 93 511 94 00.",
    ],
    baseLegal: [
      "Art. 71.2 Ley 36/2011, de 10 de octubre, reguladora de la jurisdicción social",
      "Decreto 196/2010, de 14 de diciembre, sobre la inspección médica del ICAM",
      "Art. 170-173 LGSS (RDLeg 8/2015): extinción de la IT por alta médica",
    ],
    contacte: [
      { label: "ICAM Barcelona", valor: "93 511 94 00" },
      { label: "ICAM Girona", valor: "97 294 23 22" },
      { label: "ICAM Lleida", valor: "97 325 43 61" },
      { label: "ICAM Tarragona", valor: "97 721 36 12" },
    ],
    url: "https://tramits.gencat.cat/ca/tramits/tramits-temes/Reclamacio-administrativa-previa-a-la-via-judicial-social-en-materia-dincapacitats-temporals",
    urlLabel: "Trámite Gencat",
  },
  {
    id: "mutua-at",
    icon: HardHat,
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-l-orange-500",
    badgeColor: "bg-orange-100 text-orange-800",
    title: "Alta de la mutua (Accidente de Trabajo)",
    subtitle: "Procedimiento especial de revisión — INSS",
    termini: "10 días hábiles",
    organisme: "INSS",
    urgencia: "Muy alta",
    resum:
      "Cuando una mutua colaboradora de la Seguridad Social emite un alta médica por contingencia profesional (accidente de trabajo o enfermedad profesional) y el trabajador no está de acuerdo, puede solicitar la revisión ante el INSS en un procedimiento especial que SUSPENDE la reincorporación al trabajo.",
    passos: [
      {
        num: 1,
        titol: "Solicitar la revisión al INSS",
        desc: "Presentar la solicitud de revisión del alta al INSS (presencialmente, por internet o por teléfono) en el plazo de 10 días hábiles desde la notificación del alta por la mutua.",
      },
      {
        num: 2,
        titol: "Suspensión automática de la reincorporación",
        desc: "IMPORTANTE: La mera presentación de la solicitud de revisión suspende automáticamente los efectos del alta (art. 4.3 RD 1430/2009). El trabajador NO debe reincorporarse al trabajo hasta que el INSS resuelva. La mutua sigue pagando la prestación en modalidad de pago delegado durante la tramitación. Debe comunicar el inicio del procedimiento a la empresa el mismo día o el día hábil siguiente.",
      },
      {
        num: 3,
        titol: "Resolución del INSS (máx. 15 días hábiles)",
        desc: "El INSS tiene un máximo de 15 días hábiles para emitir resolución (contados desde que la mutua aporta la documentación en 4 días hábiles). Puede: (a) confirmar el alta de la mutua, (b) mantener la baja por contingencia profesional, o (c) determinar la contingencia causante si hay procesos concurrentes.",
      },
      {
        num: 4,
        titol: "Si el INSS confirma el alta",
        desc: "Si el INSS confirma el alta de la mutua, el trabajador debe reincorporarse a partir de la fecha que fije la resolución. Las prestaciones percibidas durante la tramitación se considerarán indebidamente percibidas (art. 4.8 RD 1430/2009). Puede recurrir la resolución del INSS en vía administrativa (reclamación previa, 20 días hábiles) y posteriormente judicial (30 días hábiles). Esta reclamación previa posterior NO suspende la reincorporación.",
      },
      {
        num: 5,
        titol: "Si no hay respuesta en el plazo máximo",
        desc: "Si el INSS no responde en el plazo máximo de 15 días hábiles (desde la aportación de documentación por la mutua), la resolución se considera dictada con los efectos de una resolución de reclamación previa (art. 4.12 RD 1430/2009). El trabajador debe reincorporarse.",
      },
    ],
    documentacio: [
      "DNI/NIE de la persona solicitante",
      "Comunicado de alta médica emitido por la mutua",
      "Comunicado de baja original y comunicados de confirmación",
      "Informes médicos de la mutua y de la atención primaria",
      "Documentación sobre el accidente de trabajo (informe de accidente, testigos)",
    ],
    consells: [
      "La solicitud de revisión SUSPENDE la reincorporación automáticamente desde el primer momento (art. 4.3 RD 1430/2009). Junto con la disconformidad de 4 días naturales por alta del INSS >365 días, es una de las dos vías que suspenden.",
      "Presenta la solicitud el primer día hábil posible. La suspensión dura hasta la resolución del INSS (máx. 15 días hábiles desde la aportación de documentación por la mutua).",
      "Guarda copia sellada de la solicitud presentada al INSS.",
      "Si el INSS confirma el alta y no estás de acuerdo, puedes presentar reclamación previa en 20 días hábiles y posteriormente demanda judicial (30 días hábiles). Esta reclamación previa posterior NO suspende la reincorporación.",
      "Consulta con un abogado laboralista si el accidente es grave o hay discrepancias sobre la contingencia.",
    ],
    baseLegal: [
      "Art. 170.2 LGSS (RDLeg 8/2015): procedimiento de revisión de alta de mutua por AT/EP <365 días",
      "Art. 4 RD 1430/2009, de 11 de septiembre: procedimiento especial de revisión y efecto suspensivo automático (art. 4.3)",
      "Art. 4.8 RD 1430/2009: prestaciones indebidamente percibidas si el INSS confirma el alta",
      "Art. 4.12 RD 1430/2009: resolución del INSS con efectos de reclamación previa",
      "STSJ Castilla y León 20-10-2021: confirma el efecto suspensivo de la impugnación del alta de mutua",
    ],
    contacte: [
      { label: "INSS (línea general)", valor: "901 16 65 65" },
      { label: "INSS (atención gratuita)", valor: "91 542 11 76" },
    ],
    url: "https://prestaciones.seg-social.es/servicio/revision-alta-medica-incapacidad-temporal.html",
    urlLabel: "Trámite Seguridad Social",
  },
  {
    id: "inss-cc",
    icon: Building2,
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-l-green-500",
    badgeColor: "bg-green-100 text-green-800",
    title: "Alta del INSS (contingencia común, >365 días)",
    subtitle: "Reclamación previa administrativa — INSS",
    termini: "4 días naturales (disconformidad) / 20 días hábiles (rec. previa)",
    organisme: "Inspección Médica SPS → INSS → Juzgado Social",
    urgencia: "Muy alta (disconformidad: 4 días naturales)",
    resum:
      "Cuando el INSS emite un alta médica pasados los 365 días de IT, hay DOS momentos de reclamación con efectos muy diferentes. La disconformidad de 4 días naturales ante la Inspección Médica del servicio público de salud SÍ suspende la reincorporación (art. 170.3 LGSS). La reclamación previa posterior ante el INSS NO suspende.",
    passos: [
      {
        num: 1,
        titol: "Disconformidad ante la Inspección Médica (4 días NATURALES) — SUSPENDE",
        desc: "URGENTE: en el plazo de 4 días naturales desde la notificación del alta del INSS, el trabajador puede manifestar su disconformidad ante la Inspección Médica del servicio público de salud (ICAM en Cataluña). Mientras se tramita, la IT se considera prorrogada y el trabajador NO debe reincorporarse (art. 170.3 LGSS y art. 3 RD 1430/2009). Debe comunicar la disconformidad a la empresa el mismo día o el día hábil siguiente.",
      },
      {
        num: 2,
        titol: "Resolución de la Inspección Médica",
        desc: "La Inspección Médica resuelve si confirma el alta o mantiene la baja. Si confirma el alta, el trabajador debe reincorporarse desde que la resolución adquiere plenos efectos.",
      },
      {
        num: 3,
        titol: "Reclamación previa ante el INSS (20 días hábiles) — NO suspende",
        desc: "Si la Inspección Médica confirma el alta, el trabajador puede presentar reclamación previa ante el INSS en el plazo de 20 días hábiles (o directamente demanda judicial). IMPORTANTE: esta reclamación previa NO suspende la obligación de reincorporación. El trabajador debe trabajar mientras se tramita.",
      },
      {
        num: 4,
        titol: "Resolución del INSS (45 días)",
        desc: "El INSS tiene 45 días para resolver la reclamación previa. Si no responde en 45 días, se entiende desestimada por silencio administrativo negativo.",
      },
      {
        num: 5,
        titol: "Demanda judicial (si es necesario)",
        desc: "Si el INSS desestima la reclamación (o silencio), el trabajador puede presentar demanda ante el Juzgado de lo Social en el plazo de 30 días hábiles desde la notificación de la resolución o desde que se agota el plazo de silencio.",
      },
    ],
    documentacio: [
      "DNI/NIE de la persona solicitante",
      "Resolución de alta del INSS",
      "Historial médico completo (informes de especialistas, pruebas diagnósticas)",
      "Informes del médico de familia sobre el estado actual",
    ],
    consells: [
      "CLAVE: hay DOS momentos. La disconformidad de 4 días naturales ante la Inspección Médica SÍ suspende la reincorporación. La reclamación previa posterior ante el INSS NO suspende.",
      "El plazo de 4 días naturales es muy corto: empieza a contar desde la notificación del alta, incluyendo sábados y domingos.",
      "Comunica la disconformidad a la empresa el mismo día o el día hábil siguiente para evitar sanciones disciplinarias.",
      "Si el médico de familia considera que no estás en condiciones de trabajar, puede emitir un nuevo comunicado de baja por recaída.",
      "En casos complejos, valora solicitar una valoración para Incapacidad Permanente si la patología es crónica.",
    ],
    baseLegal: [
      "Art. 170.3 LGSS (RDLeg 8/2015): disconformidad de 4 días naturales suspende la reincorporación",
      "Art. 3 RD 1430/2009, de 11 de septiembre: procedimiento de disconformidad con el alta del INSS",
      "Art. 71 Ley 36/2011: reclamación previa en materia de Seguridad Social",
      "STS 17-4-2023 (EDJ 550548): la reclamación previa por CC <365 días no suspende (criterio aplicable a rec. previa posterior a resolución Inspección Médica)",
    ],
    contacte: [
      { label: "INSS (línea general)", valor: "901 16 65 65" },
      { label: "INSS (atención gratuita)", valor: "91 542 11 76" },
    ],
    url: "https://prestaciones.seg-social.es/servicio/revision-alta-medica-incapacidad-temporal.html",
    urlLabel: "Trámite Seguridad Social",
  },
  {
    id: "icam-proposta-mutua",
    icon: Shield,
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-l-rose-500",
    badgeColor: "bg-rose-100 text-rose-800",
    title: "Alta por propuesta de mutua confirmada por el ICAM (<365 días)",
    subtitle: "Reclamación administrativa previa — ICAM / Dep. Salut (Cataluña)",
    termini: "11 días hábiles",
    organisme: "ICAM / Dep. Salut",
    urgencia: "Alta",
    resum:
      "Escenario específico: la mutua presenta una propuesta motivada de alta al ICAM; el médico de familia discrepa y confirma la baja; pero el ICAM no acepta la discrepancia y dicta el alta efectiva. En este caso, el alta la ha emitido el ICAM (no la mutua directamente), de manera que la vía de reclamación es la misma que para cualquier alta del ICAM: reclamación administrativa previa al Departament de Salut en 11 días hábiles.",
    passos: [
      {
        num: 1,
        titol: "Entender quién ha emitido el alta",
        desc: "En la propuesta motivada de alta de la mutua, el alta efectiva la dicta siempre el ICAM (no la mutua). Por tanto, la vía de reclamación es contra el alta del ICAM, no contra la mutua. El alta genera efectos al día siguiente de su emisión por el ICAM.",
      },
      {
        num: 2,
        titol: "Presentar la reclamación administrativa previa (11 días hábiles)",
        desc: "El trabajador dispone de 11 días hábiles desde la notificación del alta para presentar una reclamación administrativa previa dirigida a la Dirección General de Ordenación y Regulación Sanitaria del Departament de Salut. Se puede hacer por internet (formulario Gencat) o presencialmente en cualquier registro oficial.",
      },
      {
        num: 3,
        titol: "Reincorporación mientras se recurre",
        desc: "IMPORTANTE: La reclamación NO suspende el alta. El trabajador debe reincorporarse al trabajo al día siguiente del alta mientras se espera la resolución. Si no lo hace, puede ser considerado ausencia injustificada. Excepción: si el médico de familia emite un nuevo comunicado de baja por recaída o nueva patología, el trabajador puede continuar de baja.",
      },
      {
        num: 4,
        titol: "Revisión por el ICAM (nueva evaluación)",
        desc: "El ICAM revisa la reclamación. Puede citar al trabajador para un nuevo reconocimiento médico. Si el ICAM considera que la reclamación es fundada, puede revocar el alta y emitir un nuevo comunicado de baja con efectos retroactivos desde la fecha del alta.",
      },
      {
        num: 5,
        titol: "Si la reclamación es denegada → vía judicial",
        desc: "Si el ICAM confirma el alta (o no responde), el trabajador puede presentar demanda ante el Juzgado de lo Social en el plazo de 30 días hábiles desde la notificación de la resolución denegatoria (o desde que se agota el plazo de silencio administrativo). La demanda judicial puede solicitar la nulidad del alta y el reconocimiento de la prestación de IT.",
      },
      {
        num: 6,
        titol: "Alternativa: nueva baja por recaída",
        desc: "Si el médico de familia considera que el paciente no está en condiciones de trabajar, puede emitir un nuevo comunicado de baja por recaída (misma o similar patología, dentro de los 180 días naturales). En este caso, el proceso continúa como una recaída del mismo proceso de IT. Si la recaída es por la misma patología, el INSS (a través de la mutua o el SPS) puede cuestionar si es realmente una recaída o un nuevo proceso.",
      },
    ],
    documentacio: [
      "DNI/NIE de la persona solicitante",
      "Alta médica emitida por el ICAM (no por la mutua)",
      "Informe del médico de familia donde consta la discrepancia con la propuesta de alta",
      "Historial de comunicados de confirmación de la baja",
      "Informes de especialistas que avalen la continuación de la IT",
      "Documentación de la propuesta motivada de alta de la mutua (si se dispone)",
    ],
    consells: [
      "Clave: el alta la emite el ICAM, no la mutua. La vía correcta es la reclamación al Dep. de Salut (11 días hábiles), no la revisión al INSS.",
      "El médico de familia debe documentar detalladamente la discrepancia: diagnóstico, tratamiento activo, limitaciones funcionales y pronóstico.",
      "Si el paciente tiene un especialista que no esté de acuerdo con el alta, pide un informe escrito urgente para adjuntar a la reclamación.",
      "La reclamación NO suspende la reincorporación. Si el paciente no puede trabajar, el médico de familia puede emitir un nuevo comunicado de baja por recaída o nueva patología.",
      "Si el paciente se reincorpora y empeora, el médico de familia puede emitir un nuevo comunicado de baja por recaída dentro de los 180 días naturales.",
      "En casos donde la mutua ha presentado la propuesta de alta, es recomendable que el médico de familia contacte directamente con el ICAM para explicar la situación clínica.",
      "Para casos complejos o si hay sospecha de presión indebida de la mutua, se recomienda que el paciente consulte a un abogado laboralista.",
    ],
    baseLegal: [
      "Art. 170.1 LGSS (RDLeg 8/2015): competencias del INSS y del SPS hasta los 365 días",
      "RD 1430/2009, de 11 de septiembre: procedimiento de propuesta motivada de alta de las mutuas",
      "Art. 71.2 Ley 36/2011, de 10 de octubre: reclamación previa a la vía judicial social",
      "Decreto 196/2010, de 14 de diciembre: inspección médica del ICAM en Cataluña",
      "Canal Salut (Gencat): \"Propuesta motivada de alta médica\" — procedimiento de 5 días",
    ],
    contacte: [
      { label: "ICAM Barcelona", valor: "93 511 94 00" },
      { label: "ICAM Girona", valor: "97 294 23 22" },
      { label: "ICAM Lleida", valor: "97 325 43 61" },
      { label: "ICAM Tarragona", valor: "97 721 36 12" },
    ],
    url: "https://tramits.gencat.cat/ca/tramits/tramits-temes/Reclamacio-administrativa-previa-a-la-via-judicial-social-en-materia-dincapacitats-temporals",
    urlLabel: "Trámite Gencat — Reclamación administrativa previa",
  },
  {
    id: "determinacio-contingencies",
    icon: Scale,
    color: "text-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-l-purple-500",
    badgeColor: "bg-purple-100 text-purple-800",
    title: "Determinación de contingencias",
    subtitle: "Cambiar la calificación de CC a AT/EP (o viceversa)",
    termini: "En cualquier momento",
    organisme: "INSS",
    urgencia: "Variable",
    resum:
      "Cuando el trabajador considera que su IT ha sido calificada incorrectamente (por ejemplo, como contingencia común cuando debería ser accidente de trabajo o enfermedad profesional), puede solicitar la determinación de la contingencia ante el INSS. La diferencia económica puede ser significativa: AT/EP cotiza desde el día 1 al 75% BR, mientras que CC cotiza desde el día 4 al 60%/75% BR.",
    passos: [
      {
        num: 1,
        titol: "Solicitar la determinación al INSS",
        desc: "Presentar la solicitud de determinación de la contingencia causante ante el INSS. Se puede hacer en cualquier momento durante la IT o incluso una vez extinguida. No hay plazo específico, pero es recomendable hacerlo lo antes posible.",
      },
      {
        num: 2,
        titol: "Instrucción del expediente",
        desc: "El INSS instruye el expediente, solicita informes a la mutua, a la empresa y a los servicios médicos. Puede citar al trabajador para reconocimiento médico.",
      },
      {
        num: 3,
        titol: "Resolución del INSS",
        desc: "El INSS resuelve si la contingencia es común o profesional. Si es profesional, la gestión pasa a la mutua y se recalcula la prestación desde el inicio de la baja (con efectos retroactivos).",
      },
      {
        num: 4,
        titol: "Efectos económicos retroactivos",
        desc: "Si se reconoce la contingencia profesional, el trabajador tiene derecho a la diferencia de prestación desde el primer día de baja: del 60% (CC) al 75% (AT/EP), y de los días 1-3 que no se cobran en CC.",
      },
      {
        num: 5,
        titol: "Recurso si se deniega",
        desc: "Si el INSS deniega la determinación de contingencia profesional, se puede presentar reclamación previa en 30 días y posteriormente demanda ante el Juzgado de lo Social.",
      },
    ],
    documentacio: [
      "DNI/NIE de la persona solicitante",
      "Comunicado de baja médica",
      "Informe sobre las circunstancias del accidente o exposición laboral",
      "Contrato de trabajo y descripción del puesto de trabajo",
      "Testigos del accidente (si los hay)",
      "Informes médicos que relacionen la patología con el trabajo",
    ],
    consells: [
      "La diferencia económica entre CC y AT/EP puede ser muy significativa, especialmente en bajas largas.",
      "Si el accidente ocurrió durante el teletrabajo, aplica la presunción del art. 156 LGSS (iuris tantum).",
      "En enfermedades profesionales, consulta el RD 1299/2006 (listado de enfermedades profesionales) para verificar si la patología figura.",
      "Guarda toda la documentación sobre las condiciones del puesto de trabajo (evaluación de riesgos, equipos de protección).",
      "El médico de familia puede emitir el comunicado de baja como AT si tiene indicios suficientes; la calificación definitiva la hace el INSS.",
    ],
    baseLegal: [
      "Art. 156-157 LGSS (RDLeg 8/2015): definición de accidente de trabajo y enfermedad profesional",
      "RD 1299/2006, de 10 de noviembre: cuadro de enfermedades profesionales",
      "Art. 169.1 LGSS: definición de contingencia común",
      "RD 1430/2009: procedimiento de determinación de contingencias",
    ],
    contacte: [
      { label: "INSS (línea general)", valor: "901 16 65 65" },
      { label: "INSS (atención gratuita)", valor: "91 542 11 76" },
    ],
    url: "https://prestaciones.seg-social.es/servicio/determinacion-contingencia-causante-incapacidad-temporal.html",
    urlLabel: "Trámite Seguridad Social",
  },
];
